### ISSUE TITLE
2017-Q2 2.3 The Activity Stream system add-on does not regress Page Load, Smoothness or Responsiveness in Firefox relative to Tiles [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#28]
performance meta: https://github.com/mozilla/activity-stream/issues/1977
perfherder strategy: https://github.com/mozilla/activity-stream/issues/2277
perceived performance: https://github.com/mozilla/activity-stream/issues/2005

**Comment by tspurway** [comment]
Currently, AS in Nightly meets and/or exceeds all perf expectations.

**Comment by Mardak** [comment]
Perfherder: https://mzl.la/2oD891a
From https://github.com/mozilla/activity-stream/issues/2277#issuecomment-293918372

**Comment by Mardak** [comment]
All talos tests are currently not significantly regressing (over 2%) and tart has a 15% improvement.
