### ISSUE TITLE
2017-Q2 3.4 Ability to store and query Activity Stream specific metadata in PlacesDB module [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#32]
Schema and API changes: https://bugzilla.mozilla.org/show_bug.cgi?id=1352502

**Comment by tspurway** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1352502

Patch is in review

**Comment by ncloudioj** [comment]
Sync team has given us the go-ahead call, all A-S related metadata will *not* be synced in Firefox 57.

**Comment by Mardak** [comment]
Landed
