### ISSUE TITLE
2017-Q2 4.2 Run Shield Study to prove AS is as engaging as existing about:newtab [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#34]

**Comment by emtwo** [comment]
* Figuring out whether we can do an opt-out study
* Figuring out whether we can have telemetry in the shield study Tiles variant 55+
*Targeting end of June / Beginning of July
* Will be including Pocket and 2 rows of Topsites

**Comment by Mardak** [comment]
Shield study is running
