### ISSUE TITLE
2017-Q4 3.1 Release AS Web Extension API (Newtab Content Extension) to Firefox [60%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#44]
https://github.com/mozilla/newtab-content-extension

**Comment by tspurway** [comment]
This will probably not land in Firefox 57 due to schedule constraints and feedback required from Addons team.  This is more likely a Q4 KR.

**Comment by Mardak** [comment]
Written but not landed. Needs input from other groups
