### ISSUE TITLE
2017-Q3 2.5 Implement a development/staging implementation of data pipeline to commodity AWS components (Logging 2.0) [0%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#46]
https://github.com/mozilla/ping-centre/issues/72

**Comment by tspurway** [comment]
There is some uncertainty around the Logging 2.0 infrastructure and it's suitability for our needs.  We are proceeding with a plan to "tee-off" the event pipeline into a Logging 2.0 pipeline and measure it's effectivemess

**Comment by Mardak** [comment]
Deprioritized
