### ISSUE TITLE
2017-Q3 2.2 Launch three AS pref studies in multiple Fx release channels [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#49]
Planned pref studies in Q3:
- pref on 10% in Beta 56 en-US / USA Geo
- pref on 50% of Beta 56 en-US / USA + Canada Geo
- pref on 10% in Beta 56 de-DE / Germany Geo

https://docs.google.com/document/d/1wizj95pDfb4YTc2kDxTJn5TIm7SwGetAsn1e0OgeOh4/edit

**Comment by Mardak** [comment]
Launched the studies, but ran into the shield bug killing the experiments.
