### ISSUE TITLE
2017-Q3 1.6 Implement Activity Stream on about:home [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#53]
Activity Stream will be the user experience of both about:newtab and about:home.  The challenge here will be to ensure that critical performance tests do not regress (Talos and Browser Start (Hero Element) Comparative Benchmark)

**Comment by tspurway** [comment]
I am labeling this "At Risk" because of possible regressions associated with Comparative Benchmarking and the role about:home plays.  Performance of about:home is critical.  

https://bugzilla.mozilla.org/show_bug.cgi?id=1355956

**Comment by tspurway** [comment]
The prerendering patch is in the last stages of review/testing https://github.com/mozilla/activity-stream/issues/3396

**Comment by Mardak** [comment]
It's there. It happened
