### ISSUE TITLE
2017-Q3 1.5 Implement Highlights Section in Activity Stream [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#54]
Highlights are a combination of recent bookmarks and recently visited sights, rendered in an attractive card with image and descriptive text scraped from the site.

The Highlights Section appears below Top Stories section.

**Comment by tspurway** [comment]
I am adding At Risk because of schedule risk and dependencies.  This feature is dependent on Metadata processing, and has some image caching subtleties that may cause perf regressions.  Because of this, this feature would be a candidate to defer to a later release.

**Comment by Mardak** [comment]
Did not implement the "added feature" of sub highlights selection https://github.com/mozilla/activity-stream/issues/3155
