### ISSUE TITLE
2017-Q3 1.3 Implement Top Site Customization UI [80%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#56]

**Comment by tspurway** [comment]
This includes Pin/Dismiss, Show More/Less, Add/Edit Top Site, Drag'n'Drop

**Comment by tspurway** [comment]
Note that we have separated Drag and Drop Top Site functionality and have changed that functionality to a P2 

https://github.com/mozilla/activity-stream/issues/3137

**Comment by Mardak** [comment]
No dragon drops here <img width="254" alt="image" src="https://user-images.githubusercontent.com/438537/30755550-02966606-9f7c-11e7-8220-e879eee9c7c5.png">

**Comment by tspurway** [comment]
#puns
