### ISSUE TITLE
2017-Q4 1.2 Implement Tippytop Sites Databases [50%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#57]
This KR involves categorizing and collating HD icons for Firefox's most popular sites.  Some of these sites will be deployed with the build, some will reside in S3 and will be periodically downloaded by Firefox

**Comment by tspurway** [comment]
I have marked this At Risk because of restrictions around what site metadata (and the manual customizations) that are allowed on that data.  There is user engagement risk associated with lower quality icons of major sites, especially for Default Top Sites

**Comment by Mardak** [comment]
One part was what goes into Firefox. 100% there.
The other part is S3 bucket with crawler. Didn't get to that yet.
