### ISSUE TITLE
2018-Q1  1.1 Prefs [80%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#72]
Implement newtab prefs on about:preferences instead of current popout.

Here's the [Trello Card](https://trello.com/c/kV4iQYE4/152-new-tab-firefox-home-settings-in-firefox-preferences).

![image](https://user-images.githubusercontent.com/25276/36460718-ac0e0ed2-1687-11e8-877c-684a85a9d17e.png)

![image](https://user-images.githubusercontent.com/25276/36460700-9416b554-1687-11e8-8e83-9dd8a2488842.png)

**Comment by jenn-chaulk** [comment]
Experiment and Web Extension will likely not get done for FX60 .  Ed is on leave for 2 weeks in March.   Just the items in the main preferences pane will happen for this quarter/release.  May be able to land in FX61 in later part of February.

**Comment by Mardak** [comment]
Some of the unexpected issues:
- the mix of mozilla-central about:preferences and activity-stream injected xul complicates designs and experiments
- the added functionality provided by drop downs require changes to how web extensions control new window and new tab pages
- strings and functionality were finalized late February
- localization team was also moving about:preferences to Fluent in 60

The current plan is to have the "Contents" section in "General" panel for 60 for experimentation in beta. For 61, the "Home" panel will always have "Contents" along with the moved existing homepage prefs -- initially "as is" then maybe converted to the dropdowns.

**Comment by Mardak** [comment]
The prefs have moved to about:preferences for 61 but not all of the pictured functionality has landed.

landed: home category, new tab/window options, section on/off prefs and rows for top sites
not landed: web extension in drop down, rows for all sections, restore session checkbox
