### ISSUE TITLE
2018-Q1  1.3  Weighted Highlights [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#74]
Implement at least one of the following Highlight Section data types:  Pocketed items, recently watched videos, downloads, screenshots, and synced tabs.  

[Trello Card](https://trello.com/c/0Hz8vHe2/163-i-want-to-have-weighted-highlights-pocket-stories)

**Comment by sarracini** [comment]
At least one is done: Pocket'ed items are in highlights 🎉 
Downloads are in progress
