### ISSUE TITLE
2018-Q1  3.1  Snippets [75%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#77]
Currently Snippets are implemented with custom code.  Let's rewrite the client side Snippets implementation to use Message Center.

**Comment by sarracini** [comment]
Message center is moving along nicely; there is already code landed: https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/MessageCenterFeed.jsm for an experiment.

**Comment by k88hudson** [comment]
We also landed four new targeting attributes this quarter: https://bugzilla.mozilla.org/show_bug.cgi?id=1432662
