### ISSUE TITLE
2018-Q1  4.1  Product Dashboards [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#80]
Revamped product dashboards containing at least three of:  
  - MAU/DAU by region/language/version
  - Top Site engagement by action
  - Pocket engagement by card type/action/personalization
  - Negative Pocket engagement 
  - Highlights engagement by action/card type
  - General Section engagement vs. Section Position

**Comment by ncloudioj** [comment]
Revamped product dashboards containing at least three of:  
  - [x] MAU/DAU by region/language/version
  - [x] Top Site engagement by action
  - [ ] Pocket engagement by card type/action/personalization
  - [ ] Negative Pocket engagement 
  - [x] Highlights engagement by action/card type
  - [x] General Section engagement vs. Section Position

* [System overview](https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-metrics-summary_1?p_channel=release)
* [User preferences](https://sql.telemetry.mozilla.org/dashboard/activity-stream-user-preferences_1)
