### ISSUE TITLE
2018-Q2 1.5 Undo/Restore [0%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#87]
https://bugzilla.mozilla.org/show_bug.cgi?id=1444980

**Comment by tspurway** [comment]
This is "low hanging fruit" and parity feature with old Tiles.  This is currently blocked on UX

**Comment by aaronrbenson** [comment]
Linking the Trello card: https://trello.com/c/o2alaHUI/141-i-want-to-be-able-to-undo-a-delete-action-after-ive-deleted-something-top-site-bookmark-history-item
