### ISSUE TITLE
2018-Q2 4.1   Analyze Issue of Firefox users who never see/use Activity Stream [100%]

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream-okrs#93]
Let's update our tooling, analysis and dashboards to track, model and explain why a significant portion of our user base never interacts or sees Activity Stream.

**Comment by Mardak** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1458617 landed in 62 but might be valuable to uplift to beta 61 for getting data sooner.
